In [257]:
import pandas as pd
import numpy as numpy
import sklearn.preprocessing as preprocessing
import sklearn.model_selection


In [258]:
import pickle 

def save_pickle(obj, filename):
    with open("data/" + filename, 'wb') as f:
        pickle.dump(obj, f)

def load_pickle(filename):
    with open("data/" + filename, 'rb') as f:
        return pickle.load(f)

In [259]:
data = pd.read_csv('dataset.csv')
data.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [260]:
data.shape

(4920, 18)

In [261]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB


In [262]:
data.describe()

Disease  Symptom_1  Symptom_2 Symptom_3    Symptom_4  \
count               4920       4920       4920      4920         4572   
unique                41         34         48        54           50   
top     Fungal infection   vomiting   vomiting   fatigue   high_fever   
freq                 120        822        870       726          378   

        Symptom_5 Symptom_6        Symptom_7        Symptom_8  \
count        3714      2934             2268             1944   
unique         38        32               26               21   
top      headache    nausea   abdominal_pain   abdominal_pain   
freq          348       390              264              276   

                 Symptom_9          Symptom_10     Symptom_11 Symptom_12  \
count                 1692                1512           1194        744   
unique                  22                  21             18         11   
top      yellowing_of_eyes   yellowing_of_eyes   irritability    malaise   
freq                   228                 198            120        126   

          Symptom_13   Symptom_14   Symptom_15        Symptom_16    Symptom_17  
count            504          306          240               192            72  
unique             8            4            3                 3             1  
top      muscle_pain   chest_pain   chest_pain   blood_in_sputum   muscle_pain  
freq              72           96          144                72            72

In [263]:
data.head()
data

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                       NaN                  NaN       NaN       NaN   
1                       NaN                  NaN       NaN       NaN   
2                       NaN                  NaN       NaN       NaN   
3                       NaN                  NaN       NaN       NaN   
4                       NaN                  NaN       NaN       NaN   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness       NaN       NaN   
4916                    NaN                  NaN       NaN       NaN   
4917                    NaN                  NaN       NaN       NaN   
4918   small_dents_in_nails   inflammatory_nails       NaN       NaN   
4919      yellow_crust_ooze                  NaN       NaN       NaN   

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0          NaN        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN        NaN        NaN        NaN        NaN   
2          NaN        NaN        NaN        NaN        NaN        NaN   
3          NaN        NaN        NaN        NaN        NaN        NaN   
4          NaN        NaN        NaN        NaN        NaN        NaN   
...        ...        ...        ...        ...        ...        ...   
4915       NaN        NaN        NaN        NaN        NaN        NaN   
4916       NaN        NaN        NaN        NaN        NaN        NaN   
4917       NaN        NaN        NaN        NaN        NaN        NaN   
4918       NaN        NaN        NaN        NaN        NaN        NaN   
4919       NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_15 Symptom_16 Symptom_17  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
4915        NaN        NaN        NaN  
4916        NaN        NaN        NaN  
4917        NaN        NaN        NaN  
4918        NaN        NaN        NaN  
4919        NaN        NaN    

In [264]:
data.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [265]:
drop_col = ['Symptom_12', 'Symptom_13', 'Symptom_14', 'Symptom_15', 'Symptom_16', 'Symptom_17']
data = data.drop(drop_col, axis=1)
data


Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                       NaN                  NaN       NaN       NaN   
1                       NaN                  NaN       NaN       NaN   
2                       NaN                  NaN       NaN       NaN   
3                       NaN                  NaN       NaN       NaN   
4                       NaN                  NaN       NaN       NaN   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness       NaN       NaN   
4916                    NaN                  NaN       NaN       NaN   
4917                    NaN                  NaN       NaN       NaN   
4918   small_dents_in_nails   inflammatory_nails       NaN       NaN   
4919      yellow_crust_ooze                  NaN       NaN       NaN   

     Symptom_9 Symptom_10 Symptom_11  
0          NaN        NaN        NaN  
1          NaN        NaN        NaN  
2          NaN        NaN        NaN  
3          NaN        NaN        NaN  
4          NaN        NaN        NaN  
...        ...        ...        ...  
4915       NaN        NaN        NaN  
4916       NaN        NaN        NaN  
4917       NaN        NaN        NaN  
4918       NaN        NaN        NaN  
4919       NaN        NaN        NaN  

[4920 rows x 12 columns]

In [266]:
save_pickle(drop_col,'drop_col.pkl')  

In [267]:
data['Disease'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [268]:
columns = data.columns[1:]
columns

Index(['Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4', 'Symptom_5',
       'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9', 'Symptom_10',
       'Symptom_11'],
      dtype='object')

In [269]:
nul_replace = 'No additional Symtoms'
data.fillna(nul_replace, inplace=True)
save_pickle(nul_replace, 'nul_replace.pkl')

In [270]:
x = ' sdfs  sdf  sdf s'
x= x.strip()
x

'sdfs  sdf  sdf s'

In [271]:
for col in data.columns:
    data[col] = data[col].str.strip()

In [272]:

symptoms = pd.unique(data[columns].values.ravel())

symptoms

array(['itching', 'skin_rash', 'nodal_skin_eruptions',
       'dischromic _patches', 'No additional Symtoms',
       'continuous_sneezing', 'shivering', 'chills', 'watering_from_eyes',
       'stomach_pain', 'acidity', 'ulcers_on_tongue', 'vomiting', 'cough',
       'chest_pain', 'yellowish_skin', 'nausea', 'loss_of_appetite',
       'abdominal_pain', 'yellowing_of_eyes', 'burning_micturition',
       'spotting_ urination', 'passage_of_gases', 'internal_itching',
       'indigestion', 'muscle_wasting', 'patches_in_throat', 'high_fever',
       'extra_marital_contacts', 'fatigue', 'weight_loss', 'restlessness',
       'lethargy', 'irregular_sugar_level',
       'blurred_and_distorted_vision', 'obesity', 'excessive_hunger',
       'increased_appetite', 'polyuria', 'sunken_eyes', 'dehydration',
       'diarrhoea', 'breathlessness', 'family_history', 'mucoid_sputum',
       'headache', 'dizziness', 'loss_of_balance',
       'lack_of_concentration', 'stiff_neck', 'depression',
       'irrit

In [273]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
symp = label_encoder.fit_transform(symptoms)
symp.sort()
symp




array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126])

In [274]:
save_pickle(label_encoder,'label_encoder.pkl')  

In [275]:
encodedSymp = dict(zip(symptoms, symp))
encodedSymp
save_pickle(encodedSymp,'encodedSymp.pkl')  

In [276]:
for col in columns:
    data[col] = data[col].map(encodedSymp)

In [277]:
len(data['Disease'].unique())

41

In [278]:
data

Disease  Symptom_1  Symptom_2  \
0                            Fungal infection          0          1   
1                            Fungal infection          1          2   
2                            Fungal infection          0          2   
3                            Fungal infection          0          1   
4                            Fungal infection          0          1   
...                                       ...        ...        ...   
4915  (vertigo) Paroymsal  Positional Vertigo         12         45   
4916                                     Acne          1        114   
4917                  Urinary tract infection         20        117   
4918                                Psoriasis          1         65   
4919                                 Impetigo          1         27   

      Symptom_3  Symptom_4  Symptom_5  Symptom_6  Symptom_7  Symptom_8  \
0             2          3          4          4          4          4   
1             3          4          4          4          4          4   
2             3          4          4          4          4          4   
3             3          4          4          4          4          4   
4             2          4          4          4          4          4   
...         ...        ...        ...        ...        ...        ...   
4915         16        112         47        113          4          4   
4916        115        116          4          4          4          4   
4917        118        119          4          4          4          4   
4918        120        121        122        123          4          4   
4919        124        125        126          4          4          4   

      Symptom_9  Symptom_10  Symptom_11  
0             4           4           4  
1             4           4           4  
2             4           4           4  
3             4           4           4  
4             4           4           4  
...         ...         ...         ...  
4915          4           4           4  
4916          4           4           4  
4917          4           4           4  
4918          4           4           4  
4919          4           4           4  

[4920 rows x 12 columns]

In [279]:
x= data.drop('Disease', axis=1)
y= data['Disease']
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_scaled = sc.fit_transform(x)


from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)


In [280]:
save_pickle(sc,'StandardScaler.pkl')  

In [281]:
x.iloc[505]

Symptom_1     29
Symptom_2     13
Symptom_3     27
Symptom_4     42
Symptom_5     44
Symptom_6      4
Symptom_7      4
Symptom_8      4
Symptom_9      4
Symptom_10     4
Symptom_11     4
Name: 505, dtype: int64

In [282]:
x_scaled[505]

array([ 0.25323444, -0.69762926, -0.55905817, -0.083699  ,  0.20180834,
       -0.78899988, -0.72609974, -0.62287246, -0.57445712, -0.60062101,
       -0.53347722])

In [283]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: Disease, Length: 4920, dtype: object

In [284]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42,max_depth=20)
model.fit(x_train, y_train)

RandomForestClassifier(max_depth=20, random_state=42)

In [285]:
save_pickle(model,'model.pkl')  

In [286]:
y_pred = model.predict(x_test)
y_pred

array(['Acne', 'Acne', 'Hyperthyroidism', 'AIDS', 'Chronic cholestasis',
       'Hypertension', 'Hypoglycemia', 'Arthritis', 'Hepatitis B',
       'Migraine', 'Urinary tract infection', 'Diabetes', 'Hepatitis D',
       'Psoriasis', 'Alcoholic hepatitis', 'Alcoholic hepatitis',
       'Dimorphic hemmorhoids(piles)', 'Hepatitis E', 'Diabetes',
       'Cervical spondylosis', 'Bronchial Asthma', 'hepatitis A',
       'Hepatitis B', 'Bronchial Asthma', 'Allergy', 'Hepatitis C',
       'Pneumonia', 'Migraine', 'Hypothyroidism', 'Migraine',
       'Chronic cholestasis', 'Hepatitis B', 'Gastroenteritis',
       'Hepatitis E', 'Varicose veins', 'Migraine', 'Jaundice',
       'Drug Reaction', 'Pneumonia', 'Urinary tract infection',
       'Hepatitis C', '(vertigo) Paroymsal  Positional Vertigo',
       'Hypertension', 'Diabetes', 'Jaundice', 'Gastroenteritis',
       'Hypoglycemia', 'Hepatitis B', 'Psoriasis', 'Psoriasis',
       'Heart attack', 'Tuberculosis', 'Varicose veins', 'Allergy',
    

In [287]:
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Confusion matrix:", confusion_matrix(y_test, y_pred))
print("Precision score:", precision_score(y_test, y_pred,average='weighted'))
model_score = model.score(x_test, y_pred)

print("Model score:", model_score)

Accuracy score: 1.0
Confusion matrix: [[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]
Precision score: 1.0
Model score: 1.0


## predicting based on the user input sample using the trained model

In [288]:
sample = pd.read_csv('dataset.csv')
sample = sample.iloc[4000].to_dict()
print(sample)
series=pd.Series(sample)
sample = pd.DataFrame([series])
sample.fillna(nul_replace, inplace=True)
for col in sample.columns:
    sample[col] = sample[col].str.strip()
sample


{'Disease': 'Hepatitis E', 'Symptom_1': ' joint_pain', 'Symptom_2': ' vomiting', 'Symptom_3': ' fatigue', 'Symptom_4': ' high_fever', 'Symptom_5': ' yellowish_skin', 'Symptom_6': ' dark_urine', 'Symptom_7': ' nausea', 'Symptom_8': ' loss_of_appetite', 'Symptom_9': ' abdominal_pain', 'Symptom_10': ' yellowing_of_eyes', 'Symptom_11': ' acute_liver_failure', 'Symptom_12': ' coma', 'Symptom_13': ' stomach_bleeding', 'Symptom_14': nan, 'Symptom_15': nan, 'Symptom_16': nan, 'Symptom_17': nan}


C:\Users\varun\AppData\Local\Temp\ipykernel_31596\2761218712.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No additional Symtoms' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  sample.fillna(nul_replace, inplace=True)


Disease   Symptom_1 Symptom_2 Symptom_3   Symptom_4       Symptom_5  \
0  Hepatitis E  joint_pain  vomiting   fatigue  high_fever  yellowish_skin   

    Symptom_6 Symptom_7         Symptom_8       Symptom_9         Symptom_10  \
0  dark_urine    nausea  loss_of_appetite  abdominal_pain  yellowing_of_eyes   

            Symptom_11 Symptom_12        Symptom_13             Symptom_14  \
0  acute_liver_failure       coma  stomach_bleeding  No additional Symtoms   

              Symptom_15             Symptom_16             Symptom_17  
0  No additional Symtoms  No additional Symtoms  No additional Symtoms

In [289]:
# load pickel 
drop_col_l = load_pickle('drop_col.pkl')
encoded_symptoms = load_pickle('encodedSymp.pkl')
StandardScaler = load_pickle('StandardScaler.pkl')
model_pickle = load_pickle('model.pkl')
nul_replace = load_pickle('nul_replace.pkl')


In [290]:
sample.drop(drop_col_l, axis=1, inplace=True)
sample

Disease   Symptom_1 Symptom_2 Symptom_3   Symptom_4       Symptom_5  \
0  Hepatitis E  joint_pain  vomiting   fatigue  high_fever  yellowish_skin   

    Symptom_6 Symptom_7         Symptom_8       Symptom_9         Symptom_10  \
0  dark_urine    nausea  loss_of_appetite  abdominal_pain  yellowing_of_eyes   

            Symptom_11  
0  acute_liver_failure

In [291]:
sample.drop('Disease', axis=1, inplace=True)
for col in sample.columns:
    sample[col] = sample[col].map(encoded_symptoms)
sample    

Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0         65         12         29         27         15         58   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  
0         16         17         18          19          74

In [292]:
sample = StandardScaler.transform(sample)
sample


array([[ 1.67092467, -0.72829921, -0.50464538, -0.49765063, -0.66178754,
         0.94544458, -0.29094404, -0.14249188, -0.10584576, -0.10702587,
         1.91233687]])

In [293]:
# prediction
prediction = model_pickle.predict(sample)
print(f" Predicted Disease: {prediction[0]}")

 Predicted Disease: Hepatitis E
